[build]
  publish = "public"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[scheduled.functions]]
  path = "aggregate"
  schedule = "*/2 * * * *"
